name: CI
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '19 19 19 * *'
  workflow_dispatch:

jobs:
  standardized:
    uses: oliviertremblaynoel/gha-pipelines/.github/workflows/ci.yml@main
